// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

#include "auth.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ny {
namespace auth {
PROTOBUF_CONSTEXPR DecisionTrace::DecisionTrace(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.matched_roles_)*/{}
  , /*decltype(_impl_.matched_permissions_)*/{}
  , /*decltype(_impl_.trace_text_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.owner_shortcut_used_)*/false
  , /*decltype(_impl_.policy_version_)*/0
  , /*decltype(_impl_.decision_soure_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DecisionTraceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DecisionTraceDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DecisionTraceDefaultTypeInternal() {}
  union {
    DecisionTrace _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DecisionTraceDefaultTypeInternal _DecisionTrace_default_instance_;
PROTOBUF_CONSTEXPR CheckRequest::CheckRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.app_code_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.user_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.perm_key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.resource_type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.resource_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.request_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CheckRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CheckRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CheckRequestDefaultTypeInternal() {}
  union {
    CheckRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CheckRequestDefaultTypeInternal _CheckRequest_default_instance_;
PROTOBUF_CONSTEXPR CheckResponse::CheckResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.current_roles_)*/{}
  , /*decltype(_impl_.suggest_roles_)*/{}
  , /*decltype(_impl_.reason_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.trace_)*/nullptr
  , /*decltype(_impl_.allowed_)*/false
  , /*decltype(_impl_.deny_code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CheckResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CheckResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CheckResponseDefaultTypeInternal() {}
  union {
    CheckResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CheckResponseDefaultTypeInternal _CheckResponse_default_instance_;
}  // namespace auth
}  // namespace ny
static ::_pb::Metadata file_level_metadata_auth_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_auth_2eproto[2];
static const ::_pb::ServiceDescriptor* file_level_service_descriptors_auth_2eproto[1];

const uint32_t TableStruct_auth_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ny::auth::DecisionTrace, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ny::auth::DecisionTrace, _impl_.matched_roles_),
  PROTOBUF_FIELD_OFFSET(::ny::auth::DecisionTrace, _impl_.matched_permissions_),
  PROTOBUF_FIELD_OFFSET(::ny::auth::DecisionTrace, _impl_.owner_shortcut_used_),
  PROTOBUF_FIELD_OFFSET(::ny::auth::DecisionTrace, _impl_.policy_version_),
  PROTOBUF_FIELD_OFFSET(::ny::auth::DecisionTrace, _impl_.decision_soure_),
  PROTOBUF_FIELD_OFFSET(::ny::auth::DecisionTrace, _impl_.trace_text_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ny::auth::CheckRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ny::auth::CheckRequest, _impl_.app_code_),
  PROTOBUF_FIELD_OFFSET(::ny::auth::CheckRequest, _impl_.user_id_),
  PROTOBUF_FIELD_OFFSET(::ny::auth::CheckRequest, _impl_.perm_key_),
  PROTOBUF_FIELD_OFFSET(::ny::auth::CheckRequest, _impl_.resource_type_),
  PROTOBUF_FIELD_OFFSET(::ny::auth::CheckRequest, _impl_.resource_id_),
  PROTOBUF_FIELD_OFFSET(::ny::auth::CheckRequest, _impl_.request_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ny::auth::CheckResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ny::auth::CheckResponse, _impl_.allowed_),
  PROTOBUF_FIELD_OFFSET(::ny::auth::CheckResponse, _impl_.reason_),
  PROTOBUF_FIELD_OFFSET(::ny::auth::CheckResponse, _impl_.current_roles_),
  PROTOBUF_FIELD_OFFSET(::ny::auth::CheckResponse, _impl_.suggest_roles_),
  PROTOBUF_FIELD_OFFSET(::ny::auth::CheckResponse, _impl_.trace_),
  PROTOBUF_FIELD_OFFSET(::ny::auth::CheckResponse, _impl_.deny_code_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ny::auth::DecisionTrace)},
  { 12, -1, -1, sizeof(::ny::auth::CheckRequest)},
  { 24, -1, -1, sizeof(::ny::auth::CheckResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ny::auth::_DecisionTrace_default_instance_._instance,
  &::ny::auth::_CheckRequest_default_instance_._instance,
  &::ny::auth::_CheckResponse_default_instance_._instance,
};

const char descriptor_table_protodef_auth_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nauth.proto\022\007ny.auth\"\275\001\n\rDecisionTrace\022"
  "\025\n\rmatched_roles\030\001 \003(\t\022\033\n\023matched_permis"
  "sions\030\002 \003(\t\022\033\n\023owner_shortcut_used\030\003 \001(\010"
  "\022\026\n\016policy_version\030\004 \001(\005\022/\n\016decision_sou"
  "re\030\005 \001(\0162\027.ny.auth.DecisionSource\022\022\n\ntra"
  "ce_text\030\006 \001(\t\"\203\001\n\014CheckRequest\022\020\n\010app_co"
  "de\030\001 \001(\t\022\017\n\007user_id\030\002 \001(\t\022\020\n\010perm_key\030\003 "
  "\001(\t\022\025\n\rresource_type\030\004 \001(\t\022\023\n\013resource_i"
  "d\030\005 \001(\t\022\022\n\nrequest_id\030\006 \001(\t\"\253\001\n\rCheckRes"
  "ponse\022\017\n\007allowed\030\001 \001(\010\022\016\n\006reason\030\002 \001(\t\022\025"
  "\n\rcurrent_roles\030\003 \003(\t\022\025\n\rsuggest_roles\030\004"
  " \003(\t\022%\n\005trace\030\005 \001(\0132\026.ny.auth.DecisionTr"
  "ace\022$\n\tdeny_code\030\006 \001(\0162\021.ny.auth.DenyCod"
  "e*\265\002\n\010DenyCode\022\031\n\025DENY_CODE_UNSPECIFIED\020"
  "\000\022\020\n\014DENY_CODE_OK\020\001\022\036\n\032DENY_CODE_INVALID"
  "_ARGUMENT\020\002\022\033\n\027DENY_CODE_APP_NOT_FOUND\020\003"
  "\022\032\n\026DENY_CODE_APP_DISABLED\020\004\022\"\n\036DENY_COD"
  "E_PERMISSION_NOT_FOUND\020\005\022 \n\034DENY_CODE_RE"
  "SOURCE_NOT_FOUND\020\006\022\036\n\032DENY_CODE_USER_HAS"
  "_NO_ROLE\020\007\022\037\n\033DENY_CODE_PERMISSION_DENIE"
  "D\020\010\022\034\n\030DENY_CODE_INTERNAL_ERROR\020\t*~\n\016Dec"
  "isionSource\022\037\n\033DECISION_SOURCE_UNSPECIFI"
  "ED\020\000\022\026\n\022DECISION_SOURCE_DB\020\001\022\031\n\025DECISION"
  "_SOURCE_CACHE\020\002\022\030\n\024DECISION_SOURCE_SEED\020"
  "\0032E\n\013AuthService\0226\n\005Check\022\025.ny.auth.Chec"
  "kRequest\032\026.ny.auth.CheckResponseB\003\200\001\001b\006p"
  "roto3"
  ;
static ::_pbi::once_flag descriptor_table_auth_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_auth_2eproto = {
    false, false, 1045, descriptor_table_protodef_auth_2eproto,
    "auth.proto",
    &descriptor_table_auth_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_auth_2eproto::offsets,
    file_level_metadata_auth_2eproto, file_level_enum_descriptors_auth_2eproto,
    file_level_service_descriptors_auth_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_auth_2eproto_getter() {
  return &descriptor_table_auth_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_auth_2eproto(&descriptor_table_auth_2eproto);
namespace ny {
namespace auth {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DenyCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_auth_2eproto);
  return file_level_enum_descriptors_auth_2eproto[0];
}
bool DenyCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DecisionSource_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_auth_2eproto);
  return file_level_enum_descriptors_auth_2eproto[1];
}
bool DecisionSource_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class DecisionTrace::_Internal {
 public:
};

DecisionTrace::DecisionTrace(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ny.auth.DecisionTrace)
}
DecisionTrace::DecisionTrace(const DecisionTrace& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DecisionTrace* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.matched_roles_){from._impl_.matched_roles_}
    , decltype(_impl_.matched_permissions_){from._impl_.matched_permissions_}
    , decltype(_impl_.trace_text_){}
    , decltype(_impl_.owner_shortcut_used_){}
    , decltype(_impl_.policy_version_){}
    , decltype(_impl_.decision_soure_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.trace_text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.trace_text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_trace_text().empty()) {
    _this->_impl_.trace_text_.Set(from._internal_trace_text(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.owner_shortcut_used_, &from._impl_.owner_shortcut_used_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.decision_soure_) -
    reinterpret_cast<char*>(&_impl_.owner_shortcut_used_)) + sizeof(_impl_.decision_soure_));
  // @@protoc_insertion_point(copy_constructor:ny.auth.DecisionTrace)
}

inline void DecisionTrace::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.matched_roles_){arena}
    , decltype(_impl_.matched_permissions_){arena}
    , decltype(_impl_.trace_text_){}
    , decltype(_impl_.owner_shortcut_used_){false}
    , decltype(_impl_.policy_version_){0}
    , decltype(_impl_.decision_soure_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.trace_text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.trace_text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DecisionTrace::~DecisionTrace() {
  // @@protoc_insertion_point(destructor:ny.auth.DecisionTrace)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DecisionTrace::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.matched_roles_.~RepeatedPtrField();
  _impl_.matched_permissions_.~RepeatedPtrField();
  _impl_.trace_text_.Destroy();
}

void DecisionTrace::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DecisionTrace::Clear() {
// @@protoc_insertion_point(message_clear_start:ny.auth.DecisionTrace)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.matched_roles_.Clear();
  _impl_.matched_permissions_.Clear();
  _impl_.trace_text_.ClearToEmpty();
  ::memset(&_impl_.owner_shortcut_used_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.decision_soure_) -
      reinterpret_cast<char*>(&_impl_.owner_shortcut_used_)) + sizeof(_impl_.decision_soure_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DecisionTrace::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string matched_roles = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_matched_roles();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "ny.auth.DecisionTrace.matched_roles"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated string matched_permissions = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_matched_permissions();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "ny.auth.DecisionTrace.matched_permissions"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      // bool owner_shortcut_used = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.owner_shortcut_used_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 policy_version = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.policy_version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ny.auth.DecisionSource decision_soure = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_decision_soure(static_cast<::ny::auth::DecisionSource>(val));
        } else
          goto handle_unusual;
        continue;
      // string trace_text = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_trace_text();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ny.auth.DecisionTrace.trace_text"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DecisionTrace::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ny.auth.DecisionTrace)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string matched_roles = 1;
  for (int i = 0, n = this->_internal_matched_roles_size(); i < n; i++) {
    const auto& s = this->_internal_matched_roles(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ny.auth.DecisionTrace.matched_roles");
    target = stream->WriteString(1, s, target);
  }

  // repeated string matched_permissions = 2;
  for (int i = 0, n = this->_internal_matched_permissions_size(); i < n; i++) {
    const auto& s = this->_internal_matched_permissions(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ny.auth.DecisionTrace.matched_permissions");
    target = stream->WriteString(2, s, target);
  }

  // bool owner_shortcut_used = 3;
  if (this->_internal_owner_shortcut_used() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_owner_shortcut_used(), target);
  }

  // int32 policy_version = 4;
  if (this->_internal_policy_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_policy_version(), target);
  }

  // .ny.auth.DecisionSource decision_soure = 5;
  if (this->_internal_decision_soure() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      5, this->_internal_decision_soure(), target);
  }

  // string trace_text = 6;
  if (!this->_internal_trace_text().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_trace_text().data(), static_cast<int>(this->_internal_trace_text().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ny.auth.DecisionTrace.trace_text");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_trace_text(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ny.auth.DecisionTrace)
  return target;
}

size_t DecisionTrace::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ny.auth.DecisionTrace)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string matched_roles = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.matched_roles_.size());
  for (int i = 0, n = _impl_.matched_roles_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.matched_roles_.Get(i));
  }

  // repeated string matched_permissions = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.matched_permissions_.size());
  for (int i = 0, n = _impl_.matched_permissions_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.matched_permissions_.Get(i));
  }

  // string trace_text = 6;
  if (!this->_internal_trace_text().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_trace_text());
  }

  // bool owner_shortcut_used = 3;
  if (this->_internal_owner_shortcut_used() != 0) {
    total_size += 1 + 1;
  }

  // int32 policy_version = 4;
  if (this->_internal_policy_version() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_policy_version());
  }

  // .ny.auth.DecisionSource decision_soure = 5;
  if (this->_internal_decision_soure() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_decision_soure());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DecisionTrace::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DecisionTrace::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DecisionTrace::GetClassData() const { return &_class_data_; }


void DecisionTrace::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DecisionTrace*>(&to_msg);
  auto& from = static_cast<const DecisionTrace&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ny.auth.DecisionTrace)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.matched_roles_.MergeFrom(from._impl_.matched_roles_);
  _this->_impl_.matched_permissions_.MergeFrom(from._impl_.matched_permissions_);
  if (!from._internal_trace_text().empty()) {
    _this->_internal_set_trace_text(from._internal_trace_text());
  }
  if (from._internal_owner_shortcut_used() != 0) {
    _this->_internal_set_owner_shortcut_used(from._internal_owner_shortcut_used());
  }
  if (from._internal_policy_version() != 0) {
    _this->_internal_set_policy_version(from._internal_policy_version());
  }
  if (from._internal_decision_soure() != 0) {
    _this->_internal_set_decision_soure(from._internal_decision_soure());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DecisionTrace::CopyFrom(const DecisionTrace& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ny.auth.DecisionTrace)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DecisionTrace::IsInitialized() const {
  return true;
}

void DecisionTrace::InternalSwap(DecisionTrace* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.matched_roles_.InternalSwap(&other->_impl_.matched_roles_);
  _impl_.matched_permissions_.InternalSwap(&other->_impl_.matched_permissions_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.trace_text_, lhs_arena,
      &other->_impl_.trace_text_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DecisionTrace, _impl_.decision_soure_)
      + sizeof(DecisionTrace::_impl_.decision_soure_)
      - PROTOBUF_FIELD_OFFSET(DecisionTrace, _impl_.owner_shortcut_used_)>(
          reinterpret_cast<char*>(&_impl_.owner_shortcut_used_),
          reinterpret_cast<char*>(&other->_impl_.owner_shortcut_used_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DecisionTrace::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_auth_2eproto_getter, &descriptor_table_auth_2eproto_once,
      file_level_metadata_auth_2eproto[0]);
}

// ===================================================================

class CheckRequest::_Internal {
 public:
};

CheckRequest::CheckRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ny.auth.CheckRequest)
}
CheckRequest::CheckRequest(const CheckRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CheckRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.app_code_){}
    , decltype(_impl_.user_id_){}
    , decltype(_impl_.perm_key_){}
    , decltype(_impl_.resource_type_){}
    , decltype(_impl_.resource_id_){}
    , decltype(_impl_.request_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.app_code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.app_code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_app_code().empty()) {
    _this->_impl_.app_code_.Set(from._internal_app_code(), 
      _this->GetArenaForAllocation());
  }
  _impl_.user_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.user_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_user_id().empty()) {
    _this->_impl_.user_id_.Set(from._internal_user_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.perm_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.perm_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_perm_key().empty()) {
    _this->_impl_.perm_key_.Set(from._internal_perm_key(), 
      _this->GetArenaForAllocation());
  }
  _impl_.resource_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.resource_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_resource_type().empty()) {
    _this->_impl_.resource_type_.Set(from._internal_resource_type(), 
      _this->GetArenaForAllocation());
  }
  _impl_.resource_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.resource_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_resource_id().empty()) {
    _this->_impl_.resource_id_.Set(from._internal_resource_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.request_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.request_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_request_id().empty()) {
    _this->_impl_.request_id_.Set(from._internal_request_id(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:ny.auth.CheckRequest)
}

inline void CheckRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.app_code_){}
    , decltype(_impl_.user_id_){}
    , decltype(_impl_.perm_key_){}
    , decltype(_impl_.resource_type_){}
    , decltype(_impl_.resource_id_){}
    , decltype(_impl_.request_id_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.app_code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.app_code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.user_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.user_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.perm_key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.perm_key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.resource_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.resource_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.resource_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.resource_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.request_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.request_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CheckRequest::~CheckRequest() {
  // @@protoc_insertion_point(destructor:ny.auth.CheckRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CheckRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.app_code_.Destroy();
  _impl_.user_id_.Destroy();
  _impl_.perm_key_.Destroy();
  _impl_.resource_type_.Destroy();
  _impl_.resource_id_.Destroy();
  _impl_.request_id_.Destroy();
}

void CheckRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CheckRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ny.auth.CheckRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.app_code_.ClearToEmpty();
  _impl_.user_id_.ClearToEmpty();
  _impl_.perm_key_.ClearToEmpty();
  _impl_.resource_type_.ClearToEmpty();
  _impl_.resource_id_.ClearToEmpty();
  _impl_.request_id_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CheckRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string app_code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_app_code();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ny.auth.CheckRequest.app_code"));
        } else
          goto handle_unusual;
        continue;
      // string user_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_user_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ny.auth.CheckRequest.user_id"));
        } else
          goto handle_unusual;
        continue;
      // string perm_key = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_perm_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ny.auth.CheckRequest.perm_key"));
        } else
          goto handle_unusual;
        continue;
      // string resource_type = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_resource_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ny.auth.CheckRequest.resource_type"));
        } else
          goto handle_unusual;
        continue;
      // string resource_id = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_resource_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ny.auth.CheckRequest.resource_id"));
        } else
          goto handle_unusual;
        continue;
      // string request_id = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_request_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ny.auth.CheckRequest.request_id"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CheckRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ny.auth.CheckRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string app_code = 1;
  if (!this->_internal_app_code().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_app_code().data(), static_cast<int>(this->_internal_app_code().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ny.auth.CheckRequest.app_code");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_app_code(), target);
  }

  // string user_id = 2;
  if (!this->_internal_user_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_user_id().data(), static_cast<int>(this->_internal_user_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ny.auth.CheckRequest.user_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_user_id(), target);
  }

  // string perm_key = 3;
  if (!this->_internal_perm_key().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_perm_key().data(), static_cast<int>(this->_internal_perm_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ny.auth.CheckRequest.perm_key");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_perm_key(), target);
  }

  // string resource_type = 4;
  if (!this->_internal_resource_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_resource_type().data(), static_cast<int>(this->_internal_resource_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ny.auth.CheckRequest.resource_type");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_resource_type(), target);
  }

  // string resource_id = 5;
  if (!this->_internal_resource_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_resource_id().data(), static_cast<int>(this->_internal_resource_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ny.auth.CheckRequest.resource_id");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_resource_id(), target);
  }

  // string request_id = 6;
  if (!this->_internal_request_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_request_id().data(), static_cast<int>(this->_internal_request_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ny.auth.CheckRequest.request_id");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_request_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ny.auth.CheckRequest)
  return target;
}

size_t CheckRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ny.auth.CheckRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string app_code = 1;
  if (!this->_internal_app_code().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_app_code());
  }

  // string user_id = 2;
  if (!this->_internal_user_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_user_id());
  }

  // string perm_key = 3;
  if (!this->_internal_perm_key().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_perm_key());
  }

  // string resource_type = 4;
  if (!this->_internal_resource_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_resource_type());
  }

  // string resource_id = 5;
  if (!this->_internal_resource_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_resource_id());
  }

  // string request_id = 6;
  if (!this->_internal_request_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_request_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CheckRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CheckRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CheckRequest::GetClassData() const { return &_class_data_; }


void CheckRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CheckRequest*>(&to_msg);
  auto& from = static_cast<const CheckRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ny.auth.CheckRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_app_code().empty()) {
    _this->_internal_set_app_code(from._internal_app_code());
  }
  if (!from._internal_user_id().empty()) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  if (!from._internal_perm_key().empty()) {
    _this->_internal_set_perm_key(from._internal_perm_key());
  }
  if (!from._internal_resource_type().empty()) {
    _this->_internal_set_resource_type(from._internal_resource_type());
  }
  if (!from._internal_resource_id().empty()) {
    _this->_internal_set_resource_id(from._internal_resource_id());
  }
  if (!from._internal_request_id().empty()) {
    _this->_internal_set_request_id(from._internal_request_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CheckRequest::CopyFrom(const CheckRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ny.auth.CheckRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CheckRequest::IsInitialized() const {
  return true;
}

void CheckRequest::InternalSwap(CheckRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.app_code_, lhs_arena,
      &other->_impl_.app_code_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.user_id_, lhs_arena,
      &other->_impl_.user_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.perm_key_, lhs_arena,
      &other->_impl_.perm_key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.resource_type_, lhs_arena,
      &other->_impl_.resource_type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.resource_id_, lhs_arena,
      &other->_impl_.resource_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.request_id_, lhs_arena,
      &other->_impl_.request_id_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata CheckRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_auth_2eproto_getter, &descriptor_table_auth_2eproto_once,
      file_level_metadata_auth_2eproto[1]);
}

// ===================================================================

class CheckResponse::_Internal {
 public:
  static const ::ny::auth::DecisionTrace& trace(const CheckResponse* msg);
};

const ::ny::auth::DecisionTrace&
CheckResponse::_Internal::trace(const CheckResponse* msg) {
  return *msg->_impl_.trace_;
}
CheckResponse::CheckResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ny.auth.CheckResponse)
}
CheckResponse::CheckResponse(const CheckResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CheckResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.current_roles_){from._impl_.current_roles_}
    , decltype(_impl_.suggest_roles_){from._impl_.suggest_roles_}
    , decltype(_impl_.reason_){}
    , decltype(_impl_.trace_){nullptr}
    , decltype(_impl_.allowed_){}
    , decltype(_impl_.deny_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.reason_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.reason_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_reason().empty()) {
    _this->_impl_.reason_.Set(from._internal_reason(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_trace()) {
    _this->_impl_.trace_ = new ::ny::auth::DecisionTrace(*from._impl_.trace_);
  }
  ::memcpy(&_impl_.allowed_, &from._impl_.allowed_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.deny_code_) -
    reinterpret_cast<char*>(&_impl_.allowed_)) + sizeof(_impl_.deny_code_));
  // @@protoc_insertion_point(copy_constructor:ny.auth.CheckResponse)
}

inline void CheckResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.current_roles_){arena}
    , decltype(_impl_.suggest_roles_){arena}
    , decltype(_impl_.reason_){}
    , decltype(_impl_.trace_){nullptr}
    , decltype(_impl_.allowed_){false}
    , decltype(_impl_.deny_code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.reason_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.reason_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CheckResponse::~CheckResponse() {
  // @@protoc_insertion_point(destructor:ny.auth.CheckResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CheckResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.current_roles_.~RepeatedPtrField();
  _impl_.suggest_roles_.~RepeatedPtrField();
  _impl_.reason_.Destroy();
  if (this != internal_default_instance()) delete _impl_.trace_;
}

void CheckResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CheckResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ny.auth.CheckResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.current_roles_.Clear();
  _impl_.suggest_roles_.Clear();
  _impl_.reason_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.trace_ != nullptr) {
    delete _impl_.trace_;
  }
  _impl_.trace_ = nullptr;
  ::memset(&_impl_.allowed_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.deny_code_) -
      reinterpret_cast<char*>(&_impl_.allowed_)) + sizeof(_impl_.deny_code_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CheckResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool allowed = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.allowed_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string reason = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_reason();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ny.auth.CheckResponse.reason"));
        } else
          goto handle_unusual;
        continue;
      // repeated string current_roles = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_current_roles();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "ny.auth.CheckResponse.current_roles"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated string suggest_roles = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_suggest_roles();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "ny.auth.CheckResponse.suggest_roles"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      // .ny.auth.DecisionTrace trace = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_trace(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .ny.auth.DenyCode deny_code = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_deny_code(static_cast<::ny::auth::DenyCode>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CheckResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ny.auth.CheckResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool allowed = 1;
  if (this->_internal_allowed() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_allowed(), target);
  }

  // string reason = 2;
  if (!this->_internal_reason().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_reason().data(), static_cast<int>(this->_internal_reason().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ny.auth.CheckResponse.reason");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_reason(), target);
  }

  // repeated string current_roles = 3;
  for (int i = 0, n = this->_internal_current_roles_size(); i < n; i++) {
    const auto& s = this->_internal_current_roles(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ny.auth.CheckResponse.current_roles");
    target = stream->WriteString(3, s, target);
  }

  // repeated string suggest_roles = 4;
  for (int i = 0, n = this->_internal_suggest_roles_size(); i < n; i++) {
    const auto& s = this->_internal_suggest_roles(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ny.auth.CheckResponse.suggest_roles");
    target = stream->WriteString(4, s, target);
  }

  // .ny.auth.DecisionTrace trace = 5;
  if (this->_internal_has_trace()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::trace(this),
        _Internal::trace(this).GetCachedSize(), target, stream);
  }

  // .ny.auth.DenyCode deny_code = 6;
  if (this->_internal_deny_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      6, this->_internal_deny_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ny.auth.CheckResponse)
  return target;
}

size_t CheckResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ny.auth.CheckResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string current_roles = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.current_roles_.size());
  for (int i = 0, n = _impl_.current_roles_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.current_roles_.Get(i));
  }

  // repeated string suggest_roles = 4;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.suggest_roles_.size());
  for (int i = 0, n = _impl_.suggest_roles_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.suggest_roles_.Get(i));
  }

  // string reason = 2;
  if (!this->_internal_reason().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_reason());
  }

  // .ny.auth.DecisionTrace trace = 5;
  if (this->_internal_has_trace()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.trace_);
  }

  // bool allowed = 1;
  if (this->_internal_allowed() != 0) {
    total_size += 1 + 1;
  }

  // .ny.auth.DenyCode deny_code = 6;
  if (this->_internal_deny_code() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_deny_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CheckResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CheckResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CheckResponse::GetClassData() const { return &_class_data_; }


void CheckResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CheckResponse*>(&to_msg);
  auto& from = static_cast<const CheckResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ny.auth.CheckResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.current_roles_.MergeFrom(from._impl_.current_roles_);
  _this->_impl_.suggest_roles_.MergeFrom(from._impl_.suggest_roles_);
  if (!from._internal_reason().empty()) {
    _this->_internal_set_reason(from._internal_reason());
  }
  if (from._internal_has_trace()) {
    _this->_internal_mutable_trace()->::ny::auth::DecisionTrace::MergeFrom(
        from._internal_trace());
  }
  if (from._internal_allowed() != 0) {
    _this->_internal_set_allowed(from._internal_allowed());
  }
  if (from._internal_deny_code() != 0) {
    _this->_internal_set_deny_code(from._internal_deny_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CheckResponse::CopyFrom(const CheckResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ny.auth.CheckResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CheckResponse::IsInitialized() const {
  return true;
}

void CheckResponse::InternalSwap(CheckResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.current_roles_.InternalSwap(&other->_impl_.current_roles_);
  _impl_.suggest_roles_.InternalSwap(&other->_impl_.suggest_roles_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.reason_, lhs_arena,
      &other->_impl_.reason_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CheckResponse, _impl_.deny_code_)
      + sizeof(CheckResponse::_impl_.deny_code_)
      - PROTOBUF_FIELD_OFFSET(CheckResponse, _impl_.trace_)>(
          reinterpret_cast<char*>(&_impl_.trace_),
          reinterpret_cast<char*>(&other->_impl_.trace_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CheckResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_auth_2eproto_getter, &descriptor_table_auth_2eproto_once,
      file_level_metadata_auth_2eproto[2]);
}

// ===================================================================

AuthService::~AuthService() {}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* AuthService::descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_auth_2eproto);
  return file_level_service_descriptors_auth_2eproto[0];
}

const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* AuthService::GetDescriptor() {
  return descriptor();
}

void AuthService::Check(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                         const ::ny::auth::CheckRequest*,
                         ::ny::auth::CheckResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method Check() not implemented.");
  done->Run();
}

void AuthService::CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                             ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                             const ::PROTOBUF_NAMESPACE_ID::Message* request,
                             ::PROTOBUF_NAMESPACE_ID::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), file_level_service_descriptors_auth_2eproto[0]);
  switch(method->index()) {
    case 0:
      Check(controller,
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ::ny::auth::CheckRequest*>(
                 request),
             ::PROTOBUF_NAMESPACE_ID::internal::DownCast<::ny::auth::CheckResponse*>(
                 response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& AuthService::GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::ny::auth::CheckRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::PROTOBUF_NAMESPACE_ID::Message& AuthService::GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::ny::auth::CheckResponse::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::PROTOBUF_NAMESPACE_ID::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

AuthService_Stub::AuthService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
AuthService_Stub::AuthService_Stub(
    ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
    ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::PROTOBUF_NAMESPACE_ID::Service::STUB_OWNS_CHANNEL) {}
AuthService_Stub::~AuthService_Stub() {
  if (owns_channel_) delete channel_;
}

void AuthService_Stub::Check(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                              const ::ny::auth::CheckRequest* request,
                              ::ny::auth::CheckResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace auth
}  // namespace ny
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ny::auth::DecisionTrace*
Arena::CreateMaybeMessage< ::ny::auth::DecisionTrace >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ny::auth::DecisionTrace >(arena);
}
template<> PROTOBUF_NOINLINE ::ny::auth::CheckRequest*
Arena::CreateMaybeMessage< ::ny::auth::CheckRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ny::auth::CheckRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::ny::auth::CheckResponse*
Arena::CreateMaybeMessage< ::ny::auth::CheckResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ny::auth::CheckResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
