// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_auth_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_auth_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_auth_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_auth_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_auth_2eproto;
namespace ny {
namespace auth {
class CheckRequest;
struct CheckRequestDefaultTypeInternal;
extern CheckRequestDefaultTypeInternal _CheckRequest_default_instance_;
class CheckResponse;
struct CheckResponseDefaultTypeInternal;
extern CheckResponseDefaultTypeInternal _CheckResponse_default_instance_;
class DecisionTrace;
struct DecisionTraceDefaultTypeInternal;
extern DecisionTraceDefaultTypeInternal _DecisionTrace_default_instance_;
}  // namespace auth
}  // namespace ny
PROTOBUF_NAMESPACE_OPEN
template<> ::ny::auth::CheckRequest* Arena::CreateMaybeMessage<::ny::auth::CheckRequest>(Arena*);
template<> ::ny::auth::CheckResponse* Arena::CreateMaybeMessage<::ny::auth::CheckResponse>(Arena*);
template<> ::ny::auth::DecisionTrace* Arena::CreateMaybeMessage<::ny::auth::DecisionTrace>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ny {
namespace auth {

enum DenyCode : int {
  DENY_CODE_UNSPECIFIED = 0,
  DENY_CODE_OK = 1,
  DENY_CODE_INVALID_ARGUMENT = 2,
  DENY_CODE_APP_NOT_FOUND = 3,
  DENY_CODE_APP_DISABLED = 4,
  DENY_CODE_PERMISSION_NOT_FOUND = 5,
  DENY_CODE_RESOURCE_NOT_FOUND = 6,
  DENY_CODE_USER_HAS_NO_ROLE = 7,
  DENY_CODE_PERMISSION_DENIED = 8,
  DENY_CODE_INTERNAL_ERROR = 9,
  DenyCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  DenyCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool DenyCode_IsValid(int value);
constexpr DenyCode DenyCode_MIN = DENY_CODE_UNSPECIFIED;
constexpr DenyCode DenyCode_MAX = DENY_CODE_INTERNAL_ERROR;
constexpr int DenyCode_ARRAYSIZE = DenyCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DenyCode_descriptor();
template<typename T>
inline const std::string& DenyCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DenyCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DenyCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DenyCode_descriptor(), enum_t_value);
}
inline bool DenyCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DenyCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DenyCode>(
    DenyCode_descriptor(), name, value);
}
enum DecisionSource : int {
  DECISION_SOURCE_UNSPECIFIED = 0,
  DECISION_SOURCE_DB = 1,
  DECISION_SOURCE_CACHE = 2,
  DecisionSource_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  DecisionSource_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool DecisionSource_IsValid(int value);
constexpr DecisionSource DecisionSource_MIN = DECISION_SOURCE_UNSPECIFIED;
constexpr DecisionSource DecisionSource_MAX = DECISION_SOURCE_CACHE;
constexpr int DecisionSource_ARRAYSIZE = DecisionSource_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DecisionSource_descriptor();
template<typename T>
inline const std::string& DecisionSource_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DecisionSource>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DecisionSource_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DecisionSource_descriptor(), enum_t_value);
}
inline bool DecisionSource_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DecisionSource* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DecisionSource>(
    DecisionSource_descriptor(), name, value);
}
// ===================================================================

class DecisionTrace final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ny.auth.DecisionTrace) */ {
 public:
  inline DecisionTrace() : DecisionTrace(nullptr) {}
  ~DecisionTrace() override;
  explicit PROTOBUF_CONSTEXPR DecisionTrace(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DecisionTrace(const DecisionTrace& from);
  DecisionTrace(DecisionTrace&& from) noexcept
    : DecisionTrace() {
    *this = ::std::move(from);
  }

  inline DecisionTrace& operator=(const DecisionTrace& from) {
    CopyFrom(from);
    return *this;
  }
  inline DecisionTrace& operator=(DecisionTrace&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DecisionTrace& default_instance() {
    return *internal_default_instance();
  }
  static inline const DecisionTrace* internal_default_instance() {
    return reinterpret_cast<const DecisionTrace*>(
               &_DecisionTrace_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DecisionTrace& a, DecisionTrace& b) {
    a.Swap(&b);
  }
  inline void Swap(DecisionTrace* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DecisionTrace* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DecisionTrace* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DecisionTrace>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DecisionTrace& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DecisionTrace& from) {
    DecisionTrace::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DecisionTrace* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ny.auth.DecisionTrace";
  }
  protected:
  explicit DecisionTrace(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMatchedRolesFieldNumber = 1,
    kMatchedPermissionsFieldNumber = 2,
    kTraceTextFieldNumber = 6,
    kOwnerShortcutUsedFieldNumber = 3,
    kPolicyVersionFieldNumber = 4,
    kDecisionSourceFieldNumber = 5,
  };
  // repeated string matched_roles = 1;
  int matched_roles_size() const;
  private:
  int _internal_matched_roles_size() const;
  public:
  void clear_matched_roles();
  const std::string& matched_roles(int index) const;
  std::string* mutable_matched_roles(int index);
  void set_matched_roles(int index, const std::string& value);
  void set_matched_roles(int index, std::string&& value);
  void set_matched_roles(int index, const char* value);
  void set_matched_roles(int index, const char* value, size_t size);
  std::string* add_matched_roles();
  void add_matched_roles(const std::string& value);
  void add_matched_roles(std::string&& value);
  void add_matched_roles(const char* value);
  void add_matched_roles(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& matched_roles() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_matched_roles();
  private:
  const std::string& _internal_matched_roles(int index) const;
  std::string* _internal_add_matched_roles();
  public:

  // repeated string matched_permissions = 2;
  int matched_permissions_size() const;
  private:
  int _internal_matched_permissions_size() const;
  public:
  void clear_matched_permissions();
  const std::string& matched_permissions(int index) const;
  std::string* mutable_matched_permissions(int index);
  void set_matched_permissions(int index, const std::string& value);
  void set_matched_permissions(int index, std::string&& value);
  void set_matched_permissions(int index, const char* value);
  void set_matched_permissions(int index, const char* value, size_t size);
  std::string* add_matched_permissions();
  void add_matched_permissions(const std::string& value);
  void add_matched_permissions(std::string&& value);
  void add_matched_permissions(const char* value);
  void add_matched_permissions(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& matched_permissions() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_matched_permissions();
  private:
  const std::string& _internal_matched_permissions(int index) const;
  std::string* _internal_add_matched_permissions();
  public:

  // string trace_text = 6;
  void clear_trace_text();
  const std::string& trace_text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_trace_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_trace_text();
  PROTOBUF_NODISCARD std::string* release_trace_text();
  void set_allocated_trace_text(std::string* trace_text);
  private:
  const std::string& _internal_trace_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_trace_text(const std::string& value);
  std::string* _internal_mutable_trace_text();
  public:

  // bool owner_shortcut_used = 3;
  void clear_owner_shortcut_used();
  bool owner_shortcut_used() const;
  void set_owner_shortcut_used(bool value);
  private:
  bool _internal_owner_shortcut_used() const;
  void _internal_set_owner_shortcut_used(bool value);
  public:

  // int32 policy_version = 4;
  void clear_policy_version();
  int32_t policy_version() const;
  void set_policy_version(int32_t value);
  private:
  int32_t _internal_policy_version() const;
  void _internal_set_policy_version(int32_t value);
  public:

  // .ny.auth.DecisionSource decision_source = 5;
  void clear_decision_source();
  ::ny::auth::DecisionSource decision_source() const;
  void set_decision_source(::ny::auth::DecisionSource value);
  private:
  ::ny::auth::DecisionSource _internal_decision_source() const;
  void _internal_set_decision_source(::ny::auth::DecisionSource value);
  public:

  // @@protoc_insertion_point(class_scope:ny.auth.DecisionTrace)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> matched_roles_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> matched_permissions_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr trace_text_;
    bool owner_shortcut_used_;
    int32_t policy_version_;
    int decision_source_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_auth_2eproto;
};
// -------------------------------------------------------------------

class CheckRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ny.auth.CheckRequest) */ {
 public:
  inline CheckRequest() : CheckRequest(nullptr) {}
  ~CheckRequest() override;
  explicit PROTOBUF_CONSTEXPR CheckRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CheckRequest(const CheckRequest& from);
  CheckRequest(CheckRequest&& from) noexcept
    : CheckRequest() {
    *this = ::std::move(from);
  }

  inline CheckRequest& operator=(const CheckRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CheckRequest& operator=(CheckRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CheckRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const CheckRequest* internal_default_instance() {
    return reinterpret_cast<const CheckRequest*>(
               &_CheckRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CheckRequest& a, CheckRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(CheckRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CheckRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CheckRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CheckRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CheckRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CheckRequest& from) {
    CheckRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CheckRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ny.auth.CheckRequest";
  }
  protected:
  explicit CheckRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAppCodeFieldNumber = 1,
    kUserIdFieldNumber = 2,
    kPermKeyFieldNumber = 3,
    kResourceTypeFieldNumber = 4,
    kResourceIdFieldNumber = 5,
    kRequestIdFieldNumber = 6,
  };
  // string app_code = 1;
  void clear_app_code();
  const std::string& app_code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_app_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_app_code();
  PROTOBUF_NODISCARD std::string* release_app_code();
  void set_allocated_app_code(std::string* app_code);
  private:
  const std::string& _internal_app_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_app_code(const std::string& value);
  std::string* _internal_mutable_app_code();
  public:

  // string user_id = 2;
  void clear_user_id();
  const std::string& user_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user_id();
  PROTOBUF_NODISCARD std::string* release_user_id();
  void set_allocated_user_id(std::string* user_id);
  private:
  const std::string& _internal_user_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_id(const std::string& value);
  std::string* _internal_mutable_user_id();
  public:

  // string perm_key = 3;
  void clear_perm_key();
  const std::string& perm_key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_perm_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_perm_key();
  PROTOBUF_NODISCARD std::string* release_perm_key();
  void set_allocated_perm_key(std::string* perm_key);
  private:
  const std::string& _internal_perm_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_perm_key(const std::string& value);
  std::string* _internal_mutable_perm_key();
  public:

  // string resource_type = 4;
  void clear_resource_type();
  const std::string& resource_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_resource_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_resource_type();
  PROTOBUF_NODISCARD std::string* release_resource_type();
  void set_allocated_resource_type(std::string* resource_type);
  private:
  const std::string& _internal_resource_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_resource_type(const std::string& value);
  std::string* _internal_mutable_resource_type();
  public:

  // string resource_id = 5;
  void clear_resource_id();
  const std::string& resource_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_resource_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_resource_id();
  PROTOBUF_NODISCARD std::string* release_resource_id();
  void set_allocated_resource_id(std::string* resource_id);
  private:
  const std::string& _internal_resource_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_resource_id(const std::string& value);
  std::string* _internal_mutable_resource_id();
  public:

  // string request_id = 6;
  void clear_request_id();
  const std::string& request_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_request_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_request_id();
  PROTOBUF_NODISCARD std::string* release_request_id();
  void set_allocated_request_id(std::string* request_id);
  private:
  const std::string& _internal_request_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_request_id(const std::string& value);
  std::string* _internal_mutable_request_id();
  public:

  // @@protoc_insertion_point(class_scope:ny.auth.CheckRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr app_code_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr perm_key_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr resource_type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr resource_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr request_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_auth_2eproto;
};
// -------------------------------------------------------------------

class CheckResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ny.auth.CheckResponse) */ {
 public:
  inline CheckResponse() : CheckResponse(nullptr) {}
  ~CheckResponse() override;
  explicit PROTOBUF_CONSTEXPR CheckResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CheckResponse(const CheckResponse& from);
  CheckResponse(CheckResponse&& from) noexcept
    : CheckResponse() {
    *this = ::std::move(from);
  }

  inline CheckResponse& operator=(const CheckResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CheckResponse& operator=(CheckResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CheckResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const CheckResponse* internal_default_instance() {
    return reinterpret_cast<const CheckResponse*>(
               &_CheckResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CheckResponse& a, CheckResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(CheckResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CheckResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CheckResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CheckResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CheckResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CheckResponse& from) {
    CheckResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CheckResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ny.auth.CheckResponse";
  }
  protected:
  explicit CheckResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCurrentRolesFieldNumber = 3,
    kSuggestRolesFieldNumber = 4,
    kReasonFieldNumber = 2,
    kTraceFieldNumber = 5,
    kAllowedFieldNumber = 1,
    kDenyCodeFieldNumber = 6,
  };
  // repeated string current_roles = 3;
  int current_roles_size() const;
  private:
  int _internal_current_roles_size() const;
  public:
  void clear_current_roles();
  const std::string& current_roles(int index) const;
  std::string* mutable_current_roles(int index);
  void set_current_roles(int index, const std::string& value);
  void set_current_roles(int index, std::string&& value);
  void set_current_roles(int index, const char* value);
  void set_current_roles(int index, const char* value, size_t size);
  std::string* add_current_roles();
  void add_current_roles(const std::string& value);
  void add_current_roles(std::string&& value);
  void add_current_roles(const char* value);
  void add_current_roles(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& current_roles() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_current_roles();
  private:
  const std::string& _internal_current_roles(int index) const;
  std::string* _internal_add_current_roles();
  public:

  // repeated string suggest_roles = 4;
  int suggest_roles_size() const;
  private:
  int _internal_suggest_roles_size() const;
  public:
  void clear_suggest_roles();
  const std::string& suggest_roles(int index) const;
  std::string* mutable_suggest_roles(int index);
  void set_suggest_roles(int index, const std::string& value);
  void set_suggest_roles(int index, std::string&& value);
  void set_suggest_roles(int index, const char* value);
  void set_suggest_roles(int index, const char* value, size_t size);
  std::string* add_suggest_roles();
  void add_suggest_roles(const std::string& value);
  void add_suggest_roles(std::string&& value);
  void add_suggest_roles(const char* value);
  void add_suggest_roles(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& suggest_roles() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_suggest_roles();
  private:
  const std::string& _internal_suggest_roles(int index) const;
  std::string* _internal_add_suggest_roles();
  public:

  // string reason = 2;
  void clear_reason();
  const std::string& reason() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_reason(ArgT0&& arg0, ArgT... args);
  std::string* mutable_reason();
  PROTOBUF_NODISCARD std::string* release_reason();
  void set_allocated_reason(std::string* reason);
  private:
  const std::string& _internal_reason() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_reason(const std::string& value);
  std::string* _internal_mutable_reason();
  public:

  // .ny.auth.DecisionTrace trace = 5;
  bool has_trace() const;
  private:
  bool _internal_has_trace() const;
  public:
  void clear_trace();
  const ::ny::auth::DecisionTrace& trace() const;
  PROTOBUF_NODISCARD ::ny::auth::DecisionTrace* release_trace();
  ::ny::auth::DecisionTrace* mutable_trace();
  void set_allocated_trace(::ny::auth::DecisionTrace* trace);
  private:
  const ::ny::auth::DecisionTrace& _internal_trace() const;
  ::ny::auth::DecisionTrace* _internal_mutable_trace();
  public:
  void unsafe_arena_set_allocated_trace(
      ::ny::auth::DecisionTrace* trace);
  ::ny::auth::DecisionTrace* unsafe_arena_release_trace();

  // bool allowed = 1;
  void clear_allowed();
  bool allowed() const;
  void set_allowed(bool value);
  private:
  bool _internal_allowed() const;
  void _internal_set_allowed(bool value);
  public:

  // .ny.auth.DenyCode deny_code = 6;
  void clear_deny_code();
  ::ny::auth::DenyCode deny_code() const;
  void set_deny_code(::ny::auth::DenyCode value);
  private:
  ::ny::auth::DenyCode _internal_deny_code() const;
  void _internal_set_deny_code(::ny::auth::DenyCode value);
  public:

  // @@protoc_insertion_point(class_scope:ny.auth.CheckResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> current_roles_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> suggest_roles_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr reason_;
    ::ny::auth::DecisionTrace* trace_;
    bool allowed_;
    int deny_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_auth_2eproto;
};
// ===================================================================

class AuthService_Stub;

class AuthService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline AuthService() {};
 public:
  virtual ~AuthService();

  typedef AuthService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void Check(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::ny::auth::CheckRequest* request,
                       ::ny::auth::CheckResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(AuthService);
};

class AuthService_Stub : public AuthService {
 public:
  AuthService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  AuthService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~AuthService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements AuthService ------------------------------------------

  void Check(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::ny::auth::CheckRequest* request,
                       ::ny::auth::CheckResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(AuthService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DecisionTrace

// repeated string matched_roles = 1;
inline int DecisionTrace::_internal_matched_roles_size() const {
  return _impl_.matched_roles_.size();
}
inline int DecisionTrace::matched_roles_size() const {
  return _internal_matched_roles_size();
}
inline void DecisionTrace::clear_matched_roles() {
  _impl_.matched_roles_.Clear();
}
inline std::string* DecisionTrace::add_matched_roles() {
  std::string* _s = _internal_add_matched_roles();
  // @@protoc_insertion_point(field_add_mutable:ny.auth.DecisionTrace.matched_roles)
  return _s;
}
inline const std::string& DecisionTrace::_internal_matched_roles(int index) const {
  return _impl_.matched_roles_.Get(index);
}
inline const std::string& DecisionTrace::matched_roles(int index) const {
  // @@protoc_insertion_point(field_get:ny.auth.DecisionTrace.matched_roles)
  return _internal_matched_roles(index);
}
inline std::string* DecisionTrace::mutable_matched_roles(int index) {
  // @@protoc_insertion_point(field_mutable:ny.auth.DecisionTrace.matched_roles)
  return _impl_.matched_roles_.Mutable(index);
}
inline void DecisionTrace::set_matched_roles(int index, const std::string& value) {
  _impl_.matched_roles_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:ny.auth.DecisionTrace.matched_roles)
}
inline void DecisionTrace::set_matched_roles(int index, std::string&& value) {
  _impl_.matched_roles_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:ny.auth.DecisionTrace.matched_roles)
}
inline void DecisionTrace::set_matched_roles(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.matched_roles_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ny.auth.DecisionTrace.matched_roles)
}
inline void DecisionTrace::set_matched_roles(int index, const char* value, size_t size) {
  _impl_.matched_roles_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ny.auth.DecisionTrace.matched_roles)
}
inline std::string* DecisionTrace::_internal_add_matched_roles() {
  return _impl_.matched_roles_.Add();
}
inline void DecisionTrace::add_matched_roles(const std::string& value) {
  _impl_.matched_roles_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ny.auth.DecisionTrace.matched_roles)
}
inline void DecisionTrace::add_matched_roles(std::string&& value) {
  _impl_.matched_roles_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:ny.auth.DecisionTrace.matched_roles)
}
inline void DecisionTrace::add_matched_roles(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.matched_roles_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ny.auth.DecisionTrace.matched_roles)
}
inline void DecisionTrace::add_matched_roles(const char* value, size_t size) {
  _impl_.matched_roles_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ny.auth.DecisionTrace.matched_roles)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
DecisionTrace::matched_roles() const {
  // @@protoc_insertion_point(field_list:ny.auth.DecisionTrace.matched_roles)
  return _impl_.matched_roles_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
DecisionTrace::mutable_matched_roles() {
  // @@protoc_insertion_point(field_mutable_list:ny.auth.DecisionTrace.matched_roles)
  return &_impl_.matched_roles_;
}

// repeated string matched_permissions = 2;
inline int DecisionTrace::_internal_matched_permissions_size() const {
  return _impl_.matched_permissions_.size();
}
inline int DecisionTrace::matched_permissions_size() const {
  return _internal_matched_permissions_size();
}
inline void DecisionTrace::clear_matched_permissions() {
  _impl_.matched_permissions_.Clear();
}
inline std::string* DecisionTrace::add_matched_permissions() {
  std::string* _s = _internal_add_matched_permissions();
  // @@protoc_insertion_point(field_add_mutable:ny.auth.DecisionTrace.matched_permissions)
  return _s;
}
inline const std::string& DecisionTrace::_internal_matched_permissions(int index) const {
  return _impl_.matched_permissions_.Get(index);
}
inline const std::string& DecisionTrace::matched_permissions(int index) const {
  // @@protoc_insertion_point(field_get:ny.auth.DecisionTrace.matched_permissions)
  return _internal_matched_permissions(index);
}
inline std::string* DecisionTrace::mutable_matched_permissions(int index) {
  // @@protoc_insertion_point(field_mutable:ny.auth.DecisionTrace.matched_permissions)
  return _impl_.matched_permissions_.Mutable(index);
}
inline void DecisionTrace::set_matched_permissions(int index, const std::string& value) {
  _impl_.matched_permissions_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:ny.auth.DecisionTrace.matched_permissions)
}
inline void DecisionTrace::set_matched_permissions(int index, std::string&& value) {
  _impl_.matched_permissions_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:ny.auth.DecisionTrace.matched_permissions)
}
inline void DecisionTrace::set_matched_permissions(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.matched_permissions_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ny.auth.DecisionTrace.matched_permissions)
}
inline void DecisionTrace::set_matched_permissions(int index, const char* value, size_t size) {
  _impl_.matched_permissions_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ny.auth.DecisionTrace.matched_permissions)
}
inline std::string* DecisionTrace::_internal_add_matched_permissions() {
  return _impl_.matched_permissions_.Add();
}
inline void DecisionTrace::add_matched_permissions(const std::string& value) {
  _impl_.matched_permissions_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ny.auth.DecisionTrace.matched_permissions)
}
inline void DecisionTrace::add_matched_permissions(std::string&& value) {
  _impl_.matched_permissions_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:ny.auth.DecisionTrace.matched_permissions)
}
inline void DecisionTrace::add_matched_permissions(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.matched_permissions_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ny.auth.DecisionTrace.matched_permissions)
}
inline void DecisionTrace::add_matched_permissions(const char* value, size_t size) {
  _impl_.matched_permissions_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ny.auth.DecisionTrace.matched_permissions)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
DecisionTrace::matched_permissions() const {
  // @@protoc_insertion_point(field_list:ny.auth.DecisionTrace.matched_permissions)
  return _impl_.matched_permissions_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
DecisionTrace::mutable_matched_permissions() {
  // @@protoc_insertion_point(field_mutable_list:ny.auth.DecisionTrace.matched_permissions)
  return &_impl_.matched_permissions_;
}

// bool owner_shortcut_used = 3;
inline void DecisionTrace::clear_owner_shortcut_used() {
  _impl_.owner_shortcut_used_ = false;
}
inline bool DecisionTrace::_internal_owner_shortcut_used() const {
  return _impl_.owner_shortcut_used_;
}
inline bool DecisionTrace::owner_shortcut_used() const {
  // @@protoc_insertion_point(field_get:ny.auth.DecisionTrace.owner_shortcut_used)
  return _internal_owner_shortcut_used();
}
inline void DecisionTrace::_internal_set_owner_shortcut_used(bool value) {
  
  _impl_.owner_shortcut_used_ = value;
}
inline void DecisionTrace::set_owner_shortcut_used(bool value) {
  _internal_set_owner_shortcut_used(value);
  // @@protoc_insertion_point(field_set:ny.auth.DecisionTrace.owner_shortcut_used)
}

// int32 policy_version = 4;
inline void DecisionTrace::clear_policy_version() {
  _impl_.policy_version_ = 0;
}
inline int32_t DecisionTrace::_internal_policy_version() const {
  return _impl_.policy_version_;
}
inline int32_t DecisionTrace::policy_version() const {
  // @@protoc_insertion_point(field_get:ny.auth.DecisionTrace.policy_version)
  return _internal_policy_version();
}
inline void DecisionTrace::_internal_set_policy_version(int32_t value) {
  
  _impl_.policy_version_ = value;
}
inline void DecisionTrace::set_policy_version(int32_t value) {
  _internal_set_policy_version(value);
  // @@protoc_insertion_point(field_set:ny.auth.DecisionTrace.policy_version)
}

// .ny.auth.DecisionSource decision_source = 5;
inline void DecisionTrace::clear_decision_source() {
  _impl_.decision_source_ = 0;
}
inline ::ny::auth::DecisionSource DecisionTrace::_internal_decision_source() const {
  return static_cast< ::ny::auth::DecisionSource >(_impl_.decision_source_);
}
inline ::ny::auth::DecisionSource DecisionTrace::decision_source() const {
  // @@protoc_insertion_point(field_get:ny.auth.DecisionTrace.decision_source)
  return _internal_decision_source();
}
inline void DecisionTrace::_internal_set_decision_source(::ny::auth::DecisionSource value) {
  
  _impl_.decision_source_ = value;
}
inline void DecisionTrace::set_decision_source(::ny::auth::DecisionSource value) {
  _internal_set_decision_source(value);
  // @@protoc_insertion_point(field_set:ny.auth.DecisionTrace.decision_source)
}

// string trace_text = 6;
inline void DecisionTrace::clear_trace_text() {
  _impl_.trace_text_.ClearToEmpty();
}
inline const std::string& DecisionTrace::trace_text() const {
  // @@protoc_insertion_point(field_get:ny.auth.DecisionTrace.trace_text)
  return _internal_trace_text();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DecisionTrace::set_trace_text(ArgT0&& arg0, ArgT... args) {
 
 _impl_.trace_text_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ny.auth.DecisionTrace.trace_text)
}
inline std::string* DecisionTrace::mutable_trace_text() {
  std::string* _s = _internal_mutable_trace_text();
  // @@protoc_insertion_point(field_mutable:ny.auth.DecisionTrace.trace_text)
  return _s;
}
inline const std::string& DecisionTrace::_internal_trace_text() const {
  return _impl_.trace_text_.Get();
}
inline void DecisionTrace::_internal_set_trace_text(const std::string& value) {
  
  _impl_.trace_text_.Set(value, GetArenaForAllocation());
}
inline std::string* DecisionTrace::_internal_mutable_trace_text() {
  
  return _impl_.trace_text_.Mutable(GetArenaForAllocation());
}
inline std::string* DecisionTrace::release_trace_text() {
  // @@protoc_insertion_point(field_release:ny.auth.DecisionTrace.trace_text)
  return _impl_.trace_text_.Release();
}
inline void DecisionTrace::set_allocated_trace_text(std::string* trace_text) {
  if (trace_text != nullptr) {
    
  } else {
    
  }
  _impl_.trace_text_.SetAllocated(trace_text, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.trace_text_.IsDefault()) {
    _impl_.trace_text_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ny.auth.DecisionTrace.trace_text)
}

// -------------------------------------------------------------------

// CheckRequest

// string app_code = 1;
inline void CheckRequest::clear_app_code() {
  _impl_.app_code_.ClearToEmpty();
}
inline const std::string& CheckRequest::app_code() const {
  // @@protoc_insertion_point(field_get:ny.auth.CheckRequest.app_code)
  return _internal_app_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CheckRequest::set_app_code(ArgT0&& arg0, ArgT... args) {
 
 _impl_.app_code_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ny.auth.CheckRequest.app_code)
}
inline std::string* CheckRequest::mutable_app_code() {
  std::string* _s = _internal_mutable_app_code();
  // @@protoc_insertion_point(field_mutable:ny.auth.CheckRequest.app_code)
  return _s;
}
inline const std::string& CheckRequest::_internal_app_code() const {
  return _impl_.app_code_.Get();
}
inline void CheckRequest::_internal_set_app_code(const std::string& value) {
  
  _impl_.app_code_.Set(value, GetArenaForAllocation());
}
inline std::string* CheckRequest::_internal_mutable_app_code() {
  
  return _impl_.app_code_.Mutable(GetArenaForAllocation());
}
inline std::string* CheckRequest::release_app_code() {
  // @@protoc_insertion_point(field_release:ny.auth.CheckRequest.app_code)
  return _impl_.app_code_.Release();
}
inline void CheckRequest::set_allocated_app_code(std::string* app_code) {
  if (app_code != nullptr) {
    
  } else {
    
  }
  _impl_.app_code_.SetAllocated(app_code, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.app_code_.IsDefault()) {
    _impl_.app_code_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ny.auth.CheckRequest.app_code)
}

// string user_id = 2;
inline void CheckRequest::clear_user_id() {
  _impl_.user_id_.ClearToEmpty();
}
inline const std::string& CheckRequest::user_id() const {
  // @@protoc_insertion_point(field_get:ny.auth.CheckRequest.user_id)
  return _internal_user_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CheckRequest::set_user_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.user_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ny.auth.CheckRequest.user_id)
}
inline std::string* CheckRequest::mutable_user_id() {
  std::string* _s = _internal_mutable_user_id();
  // @@protoc_insertion_point(field_mutable:ny.auth.CheckRequest.user_id)
  return _s;
}
inline const std::string& CheckRequest::_internal_user_id() const {
  return _impl_.user_id_.Get();
}
inline void CheckRequest::_internal_set_user_id(const std::string& value) {
  
  _impl_.user_id_.Set(value, GetArenaForAllocation());
}
inline std::string* CheckRequest::_internal_mutable_user_id() {
  
  return _impl_.user_id_.Mutable(GetArenaForAllocation());
}
inline std::string* CheckRequest::release_user_id() {
  // @@protoc_insertion_point(field_release:ny.auth.CheckRequest.user_id)
  return _impl_.user_id_.Release();
}
inline void CheckRequest::set_allocated_user_id(std::string* user_id) {
  if (user_id != nullptr) {
    
  } else {
    
  }
  _impl_.user_id_.SetAllocated(user_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.user_id_.IsDefault()) {
    _impl_.user_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ny.auth.CheckRequest.user_id)
}

// string perm_key = 3;
inline void CheckRequest::clear_perm_key() {
  _impl_.perm_key_.ClearToEmpty();
}
inline const std::string& CheckRequest::perm_key() const {
  // @@protoc_insertion_point(field_get:ny.auth.CheckRequest.perm_key)
  return _internal_perm_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CheckRequest::set_perm_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.perm_key_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ny.auth.CheckRequest.perm_key)
}
inline std::string* CheckRequest::mutable_perm_key() {
  std::string* _s = _internal_mutable_perm_key();
  // @@protoc_insertion_point(field_mutable:ny.auth.CheckRequest.perm_key)
  return _s;
}
inline const std::string& CheckRequest::_internal_perm_key() const {
  return _impl_.perm_key_.Get();
}
inline void CheckRequest::_internal_set_perm_key(const std::string& value) {
  
  _impl_.perm_key_.Set(value, GetArenaForAllocation());
}
inline std::string* CheckRequest::_internal_mutable_perm_key() {
  
  return _impl_.perm_key_.Mutable(GetArenaForAllocation());
}
inline std::string* CheckRequest::release_perm_key() {
  // @@protoc_insertion_point(field_release:ny.auth.CheckRequest.perm_key)
  return _impl_.perm_key_.Release();
}
inline void CheckRequest::set_allocated_perm_key(std::string* perm_key) {
  if (perm_key != nullptr) {
    
  } else {
    
  }
  _impl_.perm_key_.SetAllocated(perm_key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.perm_key_.IsDefault()) {
    _impl_.perm_key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ny.auth.CheckRequest.perm_key)
}

// string resource_type = 4;
inline void CheckRequest::clear_resource_type() {
  _impl_.resource_type_.ClearToEmpty();
}
inline const std::string& CheckRequest::resource_type() const {
  // @@protoc_insertion_point(field_get:ny.auth.CheckRequest.resource_type)
  return _internal_resource_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CheckRequest::set_resource_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.resource_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ny.auth.CheckRequest.resource_type)
}
inline std::string* CheckRequest::mutable_resource_type() {
  std::string* _s = _internal_mutable_resource_type();
  // @@protoc_insertion_point(field_mutable:ny.auth.CheckRequest.resource_type)
  return _s;
}
inline const std::string& CheckRequest::_internal_resource_type() const {
  return _impl_.resource_type_.Get();
}
inline void CheckRequest::_internal_set_resource_type(const std::string& value) {
  
  _impl_.resource_type_.Set(value, GetArenaForAllocation());
}
inline std::string* CheckRequest::_internal_mutable_resource_type() {
  
  return _impl_.resource_type_.Mutable(GetArenaForAllocation());
}
inline std::string* CheckRequest::release_resource_type() {
  // @@protoc_insertion_point(field_release:ny.auth.CheckRequest.resource_type)
  return _impl_.resource_type_.Release();
}
inline void CheckRequest::set_allocated_resource_type(std::string* resource_type) {
  if (resource_type != nullptr) {
    
  } else {
    
  }
  _impl_.resource_type_.SetAllocated(resource_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.resource_type_.IsDefault()) {
    _impl_.resource_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ny.auth.CheckRequest.resource_type)
}

// string resource_id = 5;
inline void CheckRequest::clear_resource_id() {
  _impl_.resource_id_.ClearToEmpty();
}
inline const std::string& CheckRequest::resource_id() const {
  // @@protoc_insertion_point(field_get:ny.auth.CheckRequest.resource_id)
  return _internal_resource_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CheckRequest::set_resource_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.resource_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ny.auth.CheckRequest.resource_id)
}
inline std::string* CheckRequest::mutable_resource_id() {
  std::string* _s = _internal_mutable_resource_id();
  // @@protoc_insertion_point(field_mutable:ny.auth.CheckRequest.resource_id)
  return _s;
}
inline const std::string& CheckRequest::_internal_resource_id() const {
  return _impl_.resource_id_.Get();
}
inline void CheckRequest::_internal_set_resource_id(const std::string& value) {
  
  _impl_.resource_id_.Set(value, GetArenaForAllocation());
}
inline std::string* CheckRequest::_internal_mutable_resource_id() {
  
  return _impl_.resource_id_.Mutable(GetArenaForAllocation());
}
inline std::string* CheckRequest::release_resource_id() {
  // @@protoc_insertion_point(field_release:ny.auth.CheckRequest.resource_id)
  return _impl_.resource_id_.Release();
}
inline void CheckRequest::set_allocated_resource_id(std::string* resource_id) {
  if (resource_id != nullptr) {
    
  } else {
    
  }
  _impl_.resource_id_.SetAllocated(resource_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.resource_id_.IsDefault()) {
    _impl_.resource_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ny.auth.CheckRequest.resource_id)
}

// string request_id = 6;
inline void CheckRequest::clear_request_id() {
  _impl_.request_id_.ClearToEmpty();
}
inline const std::string& CheckRequest::request_id() const {
  // @@protoc_insertion_point(field_get:ny.auth.CheckRequest.request_id)
  return _internal_request_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CheckRequest::set_request_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.request_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ny.auth.CheckRequest.request_id)
}
inline std::string* CheckRequest::mutable_request_id() {
  std::string* _s = _internal_mutable_request_id();
  // @@protoc_insertion_point(field_mutable:ny.auth.CheckRequest.request_id)
  return _s;
}
inline const std::string& CheckRequest::_internal_request_id() const {
  return _impl_.request_id_.Get();
}
inline void CheckRequest::_internal_set_request_id(const std::string& value) {
  
  _impl_.request_id_.Set(value, GetArenaForAllocation());
}
inline std::string* CheckRequest::_internal_mutable_request_id() {
  
  return _impl_.request_id_.Mutable(GetArenaForAllocation());
}
inline std::string* CheckRequest::release_request_id() {
  // @@protoc_insertion_point(field_release:ny.auth.CheckRequest.request_id)
  return _impl_.request_id_.Release();
}
inline void CheckRequest::set_allocated_request_id(std::string* request_id) {
  if (request_id != nullptr) {
    
  } else {
    
  }
  _impl_.request_id_.SetAllocated(request_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.request_id_.IsDefault()) {
    _impl_.request_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ny.auth.CheckRequest.request_id)
}

// -------------------------------------------------------------------

// CheckResponse

// bool allowed = 1;
inline void CheckResponse::clear_allowed() {
  _impl_.allowed_ = false;
}
inline bool CheckResponse::_internal_allowed() const {
  return _impl_.allowed_;
}
inline bool CheckResponse::allowed() const {
  // @@protoc_insertion_point(field_get:ny.auth.CheckResponse.allowed)
  return _internal_allowed();
}
inline void CheckResponse::_internal_set_allowed(bool value) {
  
  _impl_.allowed_ = value;
}
inline void CheckResponse::set_allowed(bool value) {
  _internal_set_allowed(value);
  // @@protoc_insertion_point(field_set:ny.auth.CheckResponse.allowed)
}

// string reason = 2;
inline void CheckResponse::clear_reason() {
  _impl_.reason_.ClearToEmpty();
}
inline const std::string& CheckResponse::reason() const {
  // @@protoc_insertion_point(field_get:ny.auth.CheckResponse.reason)
  return _internal_reason();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CheckResponse::set_reason(ArgT0&& arg0, ArgT... args) {
 
 _impl_.reason_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ny.auth.CheckResponse.reason)
}
inline std::string* CheckResponse::mutable_reason() {
  std::string* _s = _internal_mutable_reason();
  // @@protoc_insertion_point(field_mutable:ny.auth.CheckResponse.reason)
  return _s;
}
inline const std::string& CheckResponse::_internal_reason() const {
  return _impl_.reason_.Get();
}
inline void CheckResponse::_internal_set_reason(const std::string& value) {
  
  _impl_.reason_.Set(value, GetArenaForAllocation());
}
inline std::string* CheckResponse::_internal_mutable_reason() {
  
  return _impl_.reason_.Mutable(GetArenaForAllocation());
}
inline std::string* CheckResponse::release_reason() {
  // @@protoc_insertion_point(field_release:ny.auth.CheckResponse.reason)
  return _impl_.reason_.Release();
}
inline void CheckResponse::set_allocated_reason(std::string* reason) {
  if (reason != nullptr) {
    
  } else {
    
  }
  _impl_.reason_.SetAllocated(reason, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.reason_.IsDefault()) {
    _impl_.reason_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ny.auth.CheckResponse.reason)
}

// repeated string current_roles = 3;
inline int CheckResponse::_internal_current_roles_size() const {
  return _impl_.current_roles_.size();
}
inline int CheckResponse::current_roles_size() const {
  return _internal_current_roles_size();
}
inline void CheckResponse::clear_current_roles() {
  _impl_.current_roles_.Clear();
}
inline std::string* CheckResponse::add_current_roles() {
  std::string* _s = _internal_add_current_roles();
  // @@protoc_insertion_point(field_add_mutable:ny.auth.CheckResponse.current_roles)
  return _s;
}
inline const std::string& CheckResponse::_internal_current_roles(int index) const {
  return _impl_.current_roles_.Get(index);
}
inline const std::string& CheckResponse::current_roles(int index) const {
  // @@protoc_insertion_point(field_get:ny.auth.CheckResponse.current_roles)
  return _internal_current_roles(index);
}
inline std::string* CheckResponse::mutable_current_roles(int index) {
  // @@protoc_insertion_point(field_mutable:ny.auth.CheckResponse.current_roles)
  return _impl_.current_roles_.Mutable(index);
}
inline void CheckResponse::set_current_roles(int index, const std::string& value) {
  _impl_.current_roles_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:ny.auth.CheckResponse.current_roles)
}
inline void CheckResponse::set_current_roles(int index, std::string&& value) {
  _impl_.current_roles_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:ny.auth.CheckResponse.current_roles)
}
inline void CheckResponse::set_current_roles(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.current_roles_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ny.auth.CheckResponse.current_roles)
}
inline void CheckResponse::set_current_roles(int index, const char* value, size_t size) {
  _impl_.current_roles_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ny.auth.CheckResponse.current_roles)
}
inline std::string* CheckResponse::_internal_add_current_roles() {
  return _impl_.current_roles_.Add();
}
inline void CheckResponse::add_current_roles(const std::string& value) {
  _impl_.current_roles_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ny.auth.CheckResponse.current_roles)
}
inline void CheckResponse::add_current_roles(std::string&& value) {
  _impl_.current_roles_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:ny.auth.CheckResponse.current_roles)
}
inline void CheckResponse::add_current_roles(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.current_roles_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ny.auth.CheckResponse.current_roles)
}
inline void CheckResponse::add_current_roles(const char* value, size_t size) {
  _impl_.current_roles_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ny.auth.CheckResponse.current_roles)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
CheckResponse::current_roles() const {
  // @@protoc_insertion_point(field_list:ny.auth.CheckResponse.current_roles)
  return _impl_.current_roles_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
CheckResponse::mutable_current_roles() {
  // @@protoc_insertion_point(field_mutable_list:ny.auth.CheckResponse.current_roles)
  return &_impl_.current_roles_;
}

// repeated string suggest_roles = 4;
inline int CheckResponse::_internal_suggest_roles_size() const {
  return _impl_.suggest_roles_.size();
}
inline int CheckResponse::suggest_roles_size() const {
  return _internal_suggest_roles_size();
}
inline void CheckResponse::clear_suggest_roles() {
  _impl_.suggest_roles_.Clear();
}
inline std::string* CheckResponse::add_suggest_roles() {
  std::string* _s = _internal_add_suggest_roles();
  // @@protoc_insertion_point(field_add_mutable:ny.auth.CheckResponse.suggest_roles)
  return _s;
}
inline const std::string& CheckResponse::_internal_suggest_roles(int index) const {
  return _impl_.suggest_roles_.Get(index);
}
inline const std::string& CheckResponse::suggest_roles(int index) const {
  // @@protoc_insertion_point(field_get:ny.auth.CheckResponse.suggest_roles)
  return _internal_suggest_roles(index);
}
inline std::string* CheckResponse::mutable_suggest_roles(int index) {
  // @@protoc_insertion_point(field_mutable:ny.auth.CheckResponse.suggest_roles)
  return _impl_.suggest_roles_.Mutable(index);
}
inline void CheckResponse::set_suggest_roles(int index, const std::string& value) {
  _impl_.suggest_roles_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:ny.auth.CheckResponse.suggest_roles)
}
inline void CheckResponse::set_suggest_roles(int index, std::string&& value) {
  _impl_.suggest_roles_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:ny.auth.CheckResponse.suggest_roles)
}
inline void CheckResponse::set_suggest_roles(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.suggest_roles_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ny.auth.CheckResponse.suggest_roles)
}
inline void CheckResponse::set_suggest_roles(int index, const char* value, size_t size) {
  _impl_.suggest_roles_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ny.auth.CheckResponse.suggest_roles)
}
inline std::string* CheckResponse::_internal_add_suggest_roles() {
  return _impl_.suggest_roles_.Add();
}
inline void CheckResponse::add_suggest_roles(const std::string& value) {
  _impl_.suggest_roles_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ny.auth.CheckResponse.suggest_roles)
}
inline void CheckResponse::add_suggest_roles(std::string&& value) {
  _impl_.suggest_roles_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:ny.auth.CheckResponse.suggest_roles)
}
inline void CheckResponse::add_suggest_roles(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.suggest_roles_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ny.auth.CheckResponse.suggest_roles)
}
inline void CheckResponse::add_suggest_roles(const char* value, size_t size) {
  _impl_.suggest_roles_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ny.auth.CheckResponse.suggest_roles)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
CheckResponse::suggest_roles() const {
  // @@protoc_insertion_point(field_list:ny.auth.CheckResponse.suggest_roles)
  return _impl_.suggest_roles_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
CheckResponse::mutable_suggest_roles() {
  // @@protoc_insertion_point(field_mutable_list:ny.auth.CheckResponse.suggest_roles)
  return &_impl_.suggest_roles_;
}

// .ny.auth.DecisionTrace trace = 5;
inline bool CheckResponse::_internal_has_trace() const {
  return this != internal_default_instance() && _impl_.trace_ != nullptr;
}
inline bool CheckResponse::has_trace() const {
  return _internal_has_trace();
}
inline void CheckResponse::clear_trace() {
  if (GetArenaForAllocation() == nullptr && _impl_.trace_ != nullptr) {
    delete _impl_.trace_;
  }
  _impl_.trace_ = nullptr;
}
inline const ::ny::auth::DecisionTrace& CheckResponse::_internal_trace() const {
  const ::ny::auth::DecisionTrace* p = _impl_.trace_;
  return p != nullptr ? *p : reinterpret_cast<const ::ny::auth::DecisionTrace&>(
      ::ny::auth::_DecisionTrace_default_instance_);
}
inline const ::ny::auth::DecisionTrace& CheckResponse::trace() const {
  // @@protoc_insertion_point(field_get:ny.auth.CheckResponse.trace)
  return _internal_trace();
}
inline void CheckResponse::unsafe_arena_set_allocated_trace(
    ::ny::auth::DecisionTrace* trace) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.trace_);
  }
  _impl_.trace_ = trace;
  if (trace) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ny.auth.CheckResponse.trace)
}
inline ::ny::auth::DecisionTrace* CheckResponse::release_trace() {
  
  ::ny::auth::DecisionTrace* temp = _impl_.trace_;
  _impl_.trace_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::ny::auth::DecisionTrace* CheckResponse::unsafe_arena_release_trace() {
  // @@protoc_insertion_point(field_release:ny.auth.CheckResponse.trace)
  
  ::ny::auth::DecisionTrace* temp = _impl_.trace_;
  _impl_.trace_ = nullptr;
  return temp;
}
inline ::ny::auth::DecisionTrace* CheckResponse::_internal_mutable_trace() {
  
  if (_impl_.trace_ == nullptr) {
    auto* p = CreateMaybeMessage<::ny::auth::DecisionTrace>(GetArenaForAllocation());
    _impl_.trace_ = p;
  }
  return _impl_.trace_;
}
inline ::ny::auth::DecisionTrace* CheckResponse::mutable_trace() {
  ::ny::auth::DecisionTrace* _msg = _internal_mutable_trace();
  // @@protoc_insertion_point(field_mutable:ny.auth.CheckResponse.trace)
  return _msg;
}
inline void CheckResponse::set_allocated_trace(::ny::auth::DecisionTrace* trace) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.trace_;
  }
  if (trace) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(trace);
    if (message_arena != submessage_arena) {
      trace = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, trace, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.trace_ = trace;
  // @@protoc_insertion_point(field_set_allocated:ny.auth.CheckResponse.trace)
}

// .ny.auth.DenyCode deny_code = 6;
inline void CheckResponse::clear_deny_code() {
  _impl_.deny_code_ = 0;
}
inline ::ny::auth::DenyCode CheckResponse::_internal_deny_code() const {
  return static_cast< ::ny::auth::DenyCode >(_impl_.deny_code_);
}
inline ::ny::auth::DenyCode CheckResponse::deny_code() const {
  // @@protoc_insertion_point(field_get:ny.auth.CheckResponse.deny_code)
  return _internal_deny_code();
}
inline void CheckResponse::_internal_set_deny_code(::ny::auth::DenyCode value) {
  
  _impl_.deny_code_ = value;
}
inline void CheckResponse::set_deny_code(::ny::auth::DenyCode value) {
  _internal_set_deny_code(value);
  // @@protoc_insertion_point(field_set:ny.auth.CheckResponse.deny_code)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace auth
}  // namespace ny

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ny::auth::DenyCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ny::auth::DenyCode>() {
  return ::ny::auth::DenyCode_descriptor();
}
template <> struct is_proto_enum< ::ny::auth::DecisionSource> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ny::auth::DecisionSource>() {
  return ::ny::auth::DecisionSource_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_auth_2eproto
